---
- name: Configure DKIM
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: DKIM - Create timestamp for dkim_singing.conf
      set_fact:
         dkim_timestamp: "{{ lookup('pipe','date +%d%m%Y%H%M') }}"

    - name: DKIM - Make sure ldns-utils is installed
      openbsd_pkg:
        name: ldns-utils
        state: present
      tags: dkim

    - name: DKIM - Create folder for DKIM key
      file:
        path: "{{ dkim_key_folder }}"
        state: directory
        mode: '0755'
      tags: dkim

    - name: DKIM - Check if DKIM key exists
      stat:
        path: "{{ dkim_key_folder }}/{{ fqdn }}.key"
      register: dkim_key_exists

    - name: DKIM - Create DKIM key
      command: ssh-keygen -t {{ dkim_key_algo }} -f "{{ dkim_key_folder }}/{{ fqdn }}.key" -b {{ dkim_key_size }} -q -N ""
      tags: dkim
      when: not dkim_key_exists.stat.exists

    - name: DKIM - Set permissions for DKIM key
      file:
        path: "{{ dkim_key_folder }}"
        state: directory
        owner: root
        group: _rspamd
        mode: '0640'
      tags: dkim

# mail dkim record to admin
