---
- name: Configure DKIM
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
    - name: DKIM - Make sure ldns-utils is installed
      openbsd_pkg:
        name: ldns-utils
        state: present
      tags: dkim

    - name: DKIM - Create folder for DKIM key
      file:
        path: "{{ dkim_key_folder }}"
        state: directory
        mode: '0755'
      tags: dkim

    - name: DKIM - Create DKIM key
      openssh_keypair:
        path: "{{ dkim_key_folder }}/{{ fqdn }}.key"
        size: "{{ dkim_keysize }}"
      tags: dkim

    - name: DKIM - Set permissions for DKIM key
      file:
        path: "{{ dkim_key_folder }}"
        state: directory
        owner: root
        grpup: _rspamd
        mode: '0640'
      tags: dkim

    - name: DKIM - Create DKIM record
      set_fact:
         dkim_timestamp: "{{ lookup('pipe','date +%d%m%Y%H%M') }}"
         dkim_pubkey: "{{ lookup('pipe','sed -n \'2,4p\' < /etc/mail/dkim/{{ fqdn }}.key | tr -d \'\n\') }}"
         dkim_record_name: "{{ dkim_timestamp }}._domainkey"
         dkim_record_value: "v=DKIM{{ dkim_version }}; k={{ dkim_key_algo }}; p={{ dkim_pubkey }};"
      tags: dkim

    - name: DKIM - Create folder /etc/rspamd/local.d
      file:
        path: /etc/rspamd/local.d
        state: directory
        mode: '0755'
      tags: dkim

    - name: DKIM - Template dkim_signing.conf
      template:
        src: "dkim_signing.conf"
        dest: "/etc/rspamd/local.d"
      tags: dkim


# mail dkim record to admin
