---
- name: Helper script to setup DNS
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: DNS helper config - Configure /usr/local/bin/dns_config.sh
      template:
        src: "system/dns_config.sh"
        dest: "/usr/local/bin/dns_config.sh"
      register: httpd_config_results
      tags: dns-config

    - name: DNS helper - Set permissions for dns_config.sh
      file:
        path: /usr/local/bin/dns_config.sh
        state: file
        mode: '0755'
        owner: root
        group: wheel
      tags: dns-config

    - name: DNS helper - Run script
      shell: "/usr/local/bin/dns_config.sh > /tmp/dns_config.out"
      register: dns_config
      tags: dns-config

    # - name: DNS helper - Mail output to defined contact
    #   mail:
    #     to: "{{ dmarc_rua_contact }}"
    #     subject: DNS setup for "{{ fqdn }}"
    #     body: "Hello.  Please find attached hints on how to setup DNS for your mailserver."
    #     attach:
    #       - /tmp/dns_config.out
    #   delegate_to: localhost
    #   tags: dns-config
