---
- name: Configure Dovecot
  hosts: all_hosts
  user: {{ admins[0] }}
  become: true
  become_method: doas

  tasks:
    - name: Dovecot - Install packages
      openbsd_pkg:
        name: "{{ item }}"
        state: present
      with_items:
        - dovecot
        - dovecot-pigeonhole
      tags: dovecot

    - name: "Dovecot - Template {{ item }}"
      template:
        src: "dovecot/{{ item }}"
        dest: "/etc/dovecot/conf.d/{{ item }}"
      with_items:
        - 10-auth.conf
        - 10-mail.conf
        - 10-master.conf
        - 10-ssl.conf
        - 20-imap.conf
        - 20-managesieve.conf
        - 90-plugin.conf
        - 90-quota.conf
        - passwd.masterusers
      tags: dovecot
      register: dovecot_templates

    - name: "Dovecot - Template ACL"
      template:
        src: "dovecot/dovecot-acl"
        dest: "/etc/dovecot/dovecot-acl"
      tags: dovecot
      register: dovecot_templates

    - name: "Dovecot - Make aliases"
      shell: newaliases
      tags: dovecot

    - name: Dovecot - Start dovecot
      service:
        name: dovecot
        state: started
        enabled: yes
      tags: dovecot

    - name: Dovecot - Valdidate config
      shell: "/usr/local/bin/doveconf -n"
      register: dovecot_validate
      tags: dovecot

    - name: Dovecot - Restart dovecot when changed and config valid
      service:
        name: dovecot
        state: restarted
        enabled: yes
      when: 'dovecot_templates is changed and "Fatal" not in dovecot_validate.stdout'
      tags: dovecot
