---
- name: Configure Dovecot
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: Dovecot - Install packages
      openbsd_pkg:
        name:
          - dovecot-2.3.21v0
          - dovecot-pigeonhole-0.5.21v1
        state: present
      tags: dovecot

    - name: "Dovecot - Template config files"
      template:
        src: "dovecot/{{ item }}"
        dest: "/etc/dovecot/conf.d/{{ item }}"
      with_items:
        - 10-auth.conf
        - 10-mail.conf
        - 10-master.conf
        - 10-ssl.conf
        - 20-imap.conf
        - 20-managesieve.conf
        - 90-acl.conf
        - 90-plugin.conf
        - 90-quota.conf

      tags: dovecot
      register: dovecot_templates

    - name: "Dovecot - Template special files"
      template:
        src: "dovecot/{{ item }}"
        dest: "/etc/dovecot/{{ item }}"
      with_items:
        - dovecot-acl
        - passwd.masterusers
      tags: dovecot
      register: dovecot_specials

    - name: "Dovecot - Make aliases"
      shell: newaliases
      register: dovecot_newaliases
      changed_when: dovecot_newaliases.rc not in [0]
      tags: dovecot

    - name: Dovecot - Start dovecot
      service:
        name: dovecot
        state: started
        enabled: yes
      tags: dovecot

    - name: Dovecot - Valdidate config
      shell: "/usr/local/bin/doveconf -n"
      register: dovecot_validate
      changed_when: dovecot_validate.rc not in [0]
      tags: dovecot

    - name: Dovecot - Restart dovecot when changed and config valid
      service:
        name: dovecot
        state: restarted
        enabled: yes
      when: 'dovecot_templates is changed or dovecot_specials is changed and "Fatal" not in dovecot_validate.stdout'
      tags: dovecot
