---
- name: Configure easyrsa
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "easyrsa - create pki folder"
      file:
        path: "{{ easyrsa_pki_path }}"
        state: directory

    - name: "easyrsa - get required files from PKI"
      get_url:
        url: "https://{{ easyrsa_pki_pub_host }}/{{ item }}"
        dest: "{{ easyrsa_pki_path }}/{{ item }}"
        validate_certs: false
      with_items: "{{ easyrsa_pki_pub_files }}"
      tags: easyrsa
      register: easyrsa_pki_files
