---
- name: Configure httpd
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "httpd - Configure /etc/httpd-bad-locations.conf"
      template:
        src: "httpd-bad-locations.conf"
        dest: "/etc/httpd-bad-locations.conf"
      register: httpd_bad_locations_config_results
      tags: httpd

    - name: "httpd - Configure /etc/httpd.conf"
      template:
        src: "httpd.conf"
        dest: "/etc/httpd.conf"
      register: httpd_config_results
      tags: httpd

    - name: "httpd - Configure extra vhosts"
      template:
        src: "httpd.{{ item }}.conf"
        dest: "/etc/httpd.{{ item }}.conf"
      with_items: "{{ httpd_extra_vhosts }}"
      register: httpd_extra_vhosts_results
      tags: httpd

    - name: "httpd - Configure files htaccess"
      template: 
        src: "fileshtaccess"
        dest: "{{ httpd_files_htaccess_path }}"
        mode: 0640
        owner: www
        group: wheel
      register: httpd_files_htaccess_results
      tags: httpd

    - name: httpd - Valdidate config
      shell: "/usr/sbin/httpd -n"
      register: httpd_validate
      changed_when: httpd_validate.rc!=0
      tags: httpd

    - name: httpd - Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
      tags: httpd

    - name: httpd - Reload httpd
      service:
        name: httpd
        state: reloaded
      when: httpd_config_results is changed
      tags: httpd
