- name: Configure mailserver
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: Don't use TLS yet
      set_fact:
         httpd_use_tls: false

    - name: Configure base system
      import_tasks: system.yml

    - name: Patch system
      import_tasks: syspatch.yml

    - name: Configure pf
      import_tasks: pf.yml

    - name: Configure httpd
      import_tasks: httpd.yml

    - name: Configure acme-client
      import_tasks: acme-client.yml

    - name: Enable TLS usage now
      set_fact:
         httpd_use_tls: true

    - name: Configure httpd again, to use TLS
      import_tasks: httpd.yml

    - name: Configure rspamd
      import_tasks: rspamd.yml

    - name: Configure smtpd
      import_tasks: smtpd.yml

    - name: Configure dovecot
      import_tasks: dovecot.yml

    - name: Configure sieve
      import_tasks: sieve.yml

    - name: Configure mta-sts
      import_tasks: mta-sts.yml

    - name: DNS setup helper
      import_tasks: dns-setup.yml
