---
- name: Configure PF
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: PF - configure /etc/pf.conf
      template:
        src: "system/pf.conf"
        dest: "/etc/pf.conf"
      register: pf_config
      tags: pf

    - name: PF - configure SMTP white list
      template:
        src: "system/pf-smtp-white.txt"
        dest: "/etc/pf-smtp-white-input.txt"
        mode: "0440"
      register: pf_smtp_white_config
      when: pf_smtp_white_enabled
      tags: pf

    - name: PF - populate SMTP white list PF table
      shell: cat /etc/pf-smtp-white-input.txt | smtpctl spf walk | pfctl -t smtpwhite -T add -f -
      register: pf_smtp_white_populate
      when: pf_smtp_white_enabled
      tags: pf

    - name: PF - output SMTP white list PF table for smtpd use
      shell: pfctl -t smtpwhite -T show > /etc/pf-smtp-white.txt
      when: pf_smtp_white_enabled
      tags: pf

    - name: PF - set SMTP white list permissions for smtpd use
      file: 
        path: /etc/pf-smtp-white.txt
        mode: '0644'
      when: pf_smtp_white_enabled
      tags: pf


    - name: PF - download nixspam IP dump
      get_url:
         url: https://www.nixspam.net/download/nixspam-ip.dump.gz
         dest: /tmp/nixspam-ip.dump.gz
         mode: '0440'
      when: pf_nixspam_enabled
      tags: pf

    - name: PF - unpack nixspam IP dump
      shell: gunzip -f /tmp/nixspam-ip.dump.gz
      when: pf_nixspam_enabled
      tags: pf

    - name: PF - format nixspam IP dump and output to file
      shell: cat /tmp/nixspam-ip.dump | cut -f2 -d' ' | sort > /etc/pf-nixspam.txt
      register: pf_nixspam_format_result
      when: pf_nixspam_enabled
      tags: pf

    - name: PF - download pf-badhost
      get_url:
         url: https://www.geoghegan.ca/pub/pf-badhost/latest/pf-badhost.sh
         dest: /usr/local/bin/pf-badhost.sh
         mode: '0755'
      when: pf_badhost_enabled

    - name: PF - pf-badhost touch file
      file:
        path: /etc/pf-badhost.txt
        owner: _pfbadhost
        group: wheel
        mode: '0640'
      when: pf_badhost_enabled

    - name: PF - pf-badhost touch log dir
      file:
        path: /var/log/pf-badhost
        owner: _pfbadhost
        group: wheel
        mode: '0750'
        state: directory 
      when: pf_badhost_enabled

    - name: PF - pf-badhost touch log file
      file:
        path: /var/log/pf-badhost/pf-badhost.log
        owner: _pfbadhost
        group: wheel
        mode: '0640'
        state: touch
      when: pf_badhost_enabled

    - name: PF - pf-badhost cronjob
      cron:
        name: "pf-badhost cronjob"
        hour: "1~2"
        minute: "*"
        job: "/usr/local/bin/pf-badhost.sh -O openbsd -H 3"
        user: _pfbadhost
      when: pf_badhost_enabled

    - name: PF - check config
      shell: pfctl -nf /etc/pf.conf
      register: pf_result
      tags: pf

    - name: PF - activate pf config
      shell: pfctl -f /etc/pf.conf
      when: pf_result is succeeded and pf_config is changed
      tags: pf
