---
- name: Configure PF
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
    - name: "PF - configure /etc/pf.conf"
      template:
        src: "system/pf.conf"
        dest: "/etc/pf.conf"
      register: pf_config
      tags: pf

    - name: PF - check config
      shell: pfctl -nf /etc/pf.conf
      register: pf_result
      tags: pf

    - name: PF - activate pf config
      shell: pfctl -f /etc/pf.conf
      when: pf_result is succeeded and pf_config is changed
      tags: pf
