---
- name: Configure Sieve
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: Sieve - Make sure ldns-utils is installed
      openbsd_pkg:
        name: ldns-utils
        state: present
      tags: sieve

    - name: Sieve - Create folder for DKIM key
      file:
        path: "{{ sieve_folder }}"
        state: directory
        mode: '0755'
      tags: sieve

    - name: "Sieve - Template sieve report scripts"
      template:
        src: "sieve/{{ item  }}"
        dest: "{{ sieve_folder }}/{{ item }}"
      with_items:
        - report-ham.sieve
        - report-spam.sieve
      tags: sieve

    - name: Sieve - Compile sieve report scripts
      shell: "sievec {{ sieve_folder }}/{{ item }}"
      with_items:
        - report-ham.sieve
        - report-spam.sieve
      tags: sieve

    - name: "Sieve - Template sieve learn scripts"
      template:
        src: "sieve/{{ item  }}"
        dest: "{{ sieve_folder }}/{{ item }}"
      with_items:
        - sa-learn-ham.sh
        - sa-learn-spam.sh
      tags: sieve

    - name: Sieve - Set permissions on sieve learn scripts
      file:
        path: "{{ sieve_folder }}/{{ item }}"
        state: file
        mode: '0755'
      with_items:
        - sa-learn-ham.sh
        - sa-learn-spam.sh
      tags: sieve
