---
- name: Configure smtpd
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
    - name: "smtpd - Template {{ item }}"
      template:
        src: "smtpd/{{ item }}"
        dest: "/etc/mail/{{ item }}"
      with_items:
        - aliases
        - creds
        - domains
        - smtpd.conf
      tags: smtpd
      register: smtpd_templates
      tags: smtpd

    - name: "smtpd - Make aliases"
      command: newaliases
      tags: smtpd

    - name: smtpd - Restart smtpd when changed
      service:
        name: smtpd
        state: restarted
        enabled: yes
      when: smtpd_templates is changed
      tags: smtpd

    - name: smtpd - Start smtpd
      service:
        name: smtpd
        state: started
        enabled: yes
      tags: smtpd
