---
- name: Configure SSH
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: SSH - start
      service: name=sshd state=started
      tags: ssh

    - name: SSH - enable ssh
      shell: rcctl enable sshd
      tags: ssh

    - name: "SSH - set authorized keys for admin users"
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.key }}"
      with_items: "{{ admins }}"
      tags: ssh

    - name: "SSH - configure and validate /etc/ssh/sshd_config"
      template:
        src: "ssh/sshd_config"
        dest: "/etc/ssh/sshd_config"
        validate: "/usr/sbin/sshd -T -f %s"
      register: ssh_config_results
      tags: ssh

    - name: SSH - reload sshd
      service:
        name: sshd
        state: reloaded
      when: ssh_config_results is changed
      tags: ssh
