---
- name: Install system updates
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: Syspatch - install system updates
      shell: syspatch
      register: system_update_results
      tags: syspatch

    - name: Syspatch - install package updates
      openbsd_pkg:
        name: '*'
        state: latest
      register: package_update_results
      tags: syspatch

    - name: Syspatch - install extra packages
      openbsd_pkg: name={{ item }} state=present
      with_items: "{{ extra_packages }}"
      when: extra_packages is defined
      register: extra_packages_result
      tags: syspatch
