---
- name: Install system updates
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: Syspatch - install system updates
      shell: syspatch
      register: system_update_results
      failed_when: system_update_results.rc not in [ 0, 2 ]
      tags: syspatch

    - name: Syspatch - install package updates
      openbsd_pkg:
        name: '*'
        state: latest
      register: package_update_results
      tags: syspatch

    - name: Syspatch - install extra packages
      openbsd_pkg:
        name: 
          - pftop
          - rsync-3.2.7p1
          - curl
          - unzip
        state: present
      when: extra_packages is defined
      register: extra_packages_result
      tags: syspatch
