---
- name: Basic system setup
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "System - Configure /etc/{{ item }}"
      template:
        src: "templates/system/{{ item }}"
        dest: "/etc/{{ item }}"
      with_items:
        - doas.conf
        - myname
        - mygate
        - hosts
        - adduser.conf
        - login.conf
        - installurl
        - profile
        - sysctl.conf
      tags: sys

    - name: System - Create admin users with password
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: wheel
      no_log: false
      with_items: "{{ admins }}"
      tags: sys

    - name: System - Create mail users with password
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: wheel
      no_log: false
      with_items: "{{ users }}"
      tags: sys

    - name: System - Configure cronjobs
      cron:
        name: "{{ item.name }}"
        special_time: "{{ item.special_time }}"
        job: "{{ item.job }}"
      ignore_errors: true
      with_items: "{{ cronjobs }}"
      tags: sys

    - name: System - Template backup maildir script
      template:
        src: "system/mail_backup.sh"
        dest: "/usr/local/bin/mail_backup.sh"
        owner: root
        group: root
        mode: '0700'
      tags: sys
