---
- name: Basic system setup
  hosts: all_hosts
  user: puffy
  become: true
  become_method: doas

  tasks:
    - name: "System - Configure templates"
      template:
        src: "templates/system/{{ item }}"
        dest: "/etc/{{ item }}"
      with_items:
        - doas.conf
        - myname
        - mygate
        - adduser.conf
        - login.conf
        - installurl
        - profile
        - sysctl.conf
        - crontab.txt
        - resolv.conf
      tags: sys

    - name: "System - Configure network"
      template:
        src: "templates/system/hostname.if"
        dest: "/etc/hostname.{{ ext_if }}"
      register: config_network
      tags: sys

    - name: System - Restart NIC
      shell: sh /etc/netstart {{ ext_if }}
      when: config_network is changed
      register: network_restart
      failed_when: network_restart.rc > 1
      tags: sys

    - name: System - Get ifconfig for IPv4
      shell: ifconfig {{ ext_if }} | grep 'inet ' | cut -d ' ' -f 2
      register: ipv4_result
      changed_when: ipv4_result.rc not in [0]
      tags: sys

    - name: System - Get ifconfig for IPv6
      shell: ifconfig {{ ext_if }} | grep 'inet6 ' | cut -d ' ' -f 2 | cut -d '%' -f 1
      register: ipv6_result
      changed_when: ipv6_result.rc not in [0]
      tags: sys

    - name: "System - Set IP facts"
      set_fact:
        ipv4: "{{ ipv4_result.stdout }}"
        ipv6: "{{ ipv6_result.stdout }}"

    - name: "System - Configure templates"
      template:
        src: "templates/system/{{ item }}"
        dest: "/etc/{{ item }}"
      with_items:
        - hosts
      tags: sys

    - name: System - Create admin users with password
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: wheel
      no_log: false
      with_items: "{{ admins }}"
      tags: sys

    - name: System - Create mail users with password
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: wheel
      no_log: false
      with_items: "{{ users }}"
      tags: sys

    - name: System - Create pf-badhost user with password
      user:
        name: "_pfbadhost"
        password: "lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=12)"
      no_log: true
      tags: sys
      when: pf_badhost_enabled

    - name: System - Install crontab from file
      shell: cat /etc/crontab.txt | crontab -
      register: crontab_file
      changed_when: crontab_file.rc not in [0]
      tags: sys

    - name: System - Template backup maildir script
      template:
        src: "system/mail_backup.sh"
        dest: "/usr/local/bin/mail_backup.sh"
        owner: root
        group: wheel
        mode: '0700'
      tags: sys
