---
- name: Basic system setup
  hosts: all_hosts
  user: root
  become: true
  become_method: doas

  tasks:
    - name: "System - Configure /etc/{{ item }}"
      template:
        src: "templates/system/{{ item }}"
        dest: "/etc/{{ item }}"
      with_items:
        - doas.conf
        - myname
        - mygate
        - hosts
        - adduser.conf
        - login.conf
        - installurl
        - profile
        - sysctl.conf
      tags: sys

    - name: System - Create admin users with password
      command: pass=$(echo "{{ item.pass }}" ) && adduser -batch "{{ item.user }}" wheel 'admin' $pass
      ignore_errors: true
      no_log: false
      with_items: "{{ admins }}"
      tags: sys

    - name: System - Set admin users password
      command: pass=$(echo "{{ item.pass }}" ) && usermod -p $pass "{{ item.user }}"
      ignore_errors: true
      no_log: false
      with_items: "{{ admins }}"
      tags: sys

    - name: System - Create mail users with password
      command: pass=$(echo "{{ item.pass }}" ) && adduser -batch "{{ item.user }}" $pass
      ignore_errors: true
      no_log: false
      with_items: "{{ users }}"
      tags: sys

    - name: System - Set mail users password
      command: pass=$(echo "{{ item.pass }}" ) && usermod -p $pass "{{ item.user }}"
      ignore_errors: true
      no_log: false
      with_items: "{{ users }}"
      tags: sys

    - name: System - Configure cronjobs
      cron:
        name: "{{ item.name }}"
        special_time: "{{ item.special_time }}"
        job: "{{ item.job }}"
      ignore_errors: true
      with_items: "{{ cronjobs }}"
      tags: sys
