---
- name: Configure Dovecot
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
    - name: Dovecot - Install packages
      openbsd_pkg:
        name: "{{ item }}"
        state: present
      with_items:
        - dovecot
        - dovecot-pigeonhole
      tags: dovecot

    - name: "Dovecot - Template {{ item }}"
      template:
        src: "dovecot/{{ item }}"
        dest: "/etc/dovecot/conf.d/{{ item }}"
      with_items:
        - 10-auth.conf
        - 10-mail.conf
        - 10-master.conf
        - 10-ssl.conf
        - 20-imap.conf
        - 20-managesieve.conf
        - 90-plugin.conf
        - 90-quota.conf
        - passwd.masterusers
      tags: dovecot
      register: dovecot_templates
      tags: dovecot

    - name: "Dovecot - Template ACL"
      template:
        src: "dovecot/dovecot.acl"
        dest: "/etc/dovecot/dovecot.acl"
      tags: dovecot
      register: dovecot_templates
      tags: dovecot

    - name: "Dovecot - Make aliases"
      shell: newaliases
      tags: dovecot

    - name: Dovecot - Restart dovecot when changed
      service:
        name: dovecot
        state: restarted
        enabled: yes
      when: dovecot_templates|changed
      tags: dovecot

    - name: Dovecot - Start dovecot
      service:
        name: dovecot
        state: started
        enabled: yes
      tags: dovecot
