---
- name: Configure smtpd
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
  - name: "smtpd - Template {{ item }}"
    template:
      src: "smtpd/{{ item }}"
      dest: "/etc/mail/{{ item }}"
    with_items:
      - aliases
      - creds
      - domains
      - smtpd.conf
    tags: smtpd

  - name: "smtpd - make aliases"
    shell: newaliases
    tags: smtpd



# template and make aliases

# template and make creds

# template config file

# (re)start smtpd
