---
- name: basic system setup
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
  - name: "System - Configure /etc/{{ item }}"
    template:
      src: "system/{{ item }}"
      dest: "/etc/{{ item }}"
    with_items:
      - doas.conf
      - myname
      - mygate
      - hosts
      - adduser.conf
      - login.conf
      - installurl
      - profile
      - sysctl.conf
    tags: sys

  - name: System - Create admin user with password
    shell: pass=$(echo {{ admins.value.pass }} | encrypt) ; adduser -batch {{ admins.value.user }} wheel 'admin' $pass
    ignore_errors: true
    no_log: true
    with_items: admins
    tags: sys

  - name: System - Set admin user password
    shell: pass=$(echo {{ admins.value.pass }} | encrypt) ; usermod -p $pass {{ admins.value.user }}
    no_log: true
    with_items: admins
    tags: sys

  - name: System - Configure cronjobs
    cron:
      name: "{{ item.name }}"
      special_time: "{{ item.special_time }}"
      job: "{{ item.job }}"
    with_items: cronjobs
    tags: sys
