---
# template myname
# template mygate
# template hosts
# template login.conf

- name: basic system setup
  hosts: all_hosts
  user: admin
  become: true
  become_method: doas

  tasks:
  - name: configure /etc/myname
    template:
      src: system/myname
      dest: /etc/myname
    tags: sys-config

  - name: configure /etc/mygate
    template:
      src: system/mygate
      dest: /etc/mygate
    tags: sys-config

  - name: configure /etc/hosts
    template:
      src: system/hosts
      dest: /etc/hosts
    tags: sys-config

  - name: configure /etc/adduser.conf
    template:
      src: system/adduser.conf
      dest: /etc/adduser.conf
    tags: sys-config

  - name: configure /etc/login.conf
    template:
      src: system/login.conf
      dest: /etc/login.conf
    tags: sys-config

  - name: configure /etc/installurl
    template:
      src: system/installurl
      dest: /etc/installurl
    tags: sys-config

  - name: configure /etc/profile
    template:
      src: system/profile
      dest: /etc/profile
    tags: sys-config

  - name: create admin user with password
    shell: pass=$(echo {{ admin_pass }} | encrypt) ; adduser -batch {{ admin_user }} wheel 'admin' $pass
    ignore_errors: true
    no_log: true
    tags: sys-config

  - name: set admin user password
    shell: pass=$(echo {{ admin_pass}} | encrypt) ; usermod -p $pass {{ admin_user }}
    no_log: true
    tags: sys-config

  - name: cron - weekly system patches
    cron:
      name: "install system patches"
      special_time: weekly
      job: "syspatch"
    tags: sys-config

  - name: cron - weekly package updates
    cron:
      name: "install package updates"
      special_time: weekly
      job: "pkg_add -u"
    tags: sys-config

  - name: cron - refresh certs with acme-client
    cron:
      name: "refresh certs with acme-client"
      special_time: weekly
      job: "acme-client {{ fqdn }} && rcctl reload httpd"
    tags: sys-config

  - name: cron - refresh ocsp with ocspcheck
    cron:
      name: "refresh ocsp with ocspcheck"
      special_time: daily
      job: "ocspcheck -vN -o /etc/ssl/{{ fqdn }}.der /etc/ssl/{{ fqdn }}.fullchain.pem"
    tags: sys-config
