server "ns.schmidbauer.cz" {
        listen on * tls port 443

        root "htdocs/ns.schmidbauer.cz"

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/ns.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/ns.schmidbauer.cz.key"
        }

        # Allow only known locations
        location "/robots.txt"    { pass }
        location "/css/*.css"     { pass }
        location "/fonts/*.woff2" { pass }
        location "/img/*.png"  { pass }

        # EN locations
        location "/en/"           { pass }
        location "/en/index.html"     { pass }

        # DE locations
        location "/de/"           { pass }
        location "/de/index.html"     { pass }

        # CZ locations
        location "/cz/"           { pass }
        location "/cz/index.html"     { pass }

        # default redirect to /en
        location "/" {
                block return 302 "https://$HTTP_HOST/en/"
        }

}
