server "vpn.schmidbauer.cz" {
        listen on * tls port 443

        root "htdocs/vpn.schmidbauer.cz"

        {% if httpd_block_bad_locations %}include '{{ httpd_bad_locations_path }}'{% endif %}

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/vpn.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/vpn.schmidbauer.cz.key"
        }

        # Allow only known locations
        location "/robots.txt"    { pass }
        location "/css/*.css"     { pass }
        location "/fonts/*.woff2" { pass }
        location "/images/*.png"  { pass }
        location "/images/*.svg"  { pass }

        # EN locations
        location "/en/"           { pass }
        location "/en/index.html"     { pass }

        # DE locations
        location "/de/"           { pass }
        location "/de/index.html"     { pass }

        # CZ locations
        location "/cz/"           { pass }
        location "/cz/index.html"     { pass }

        # default redirect to /en
        location "/" {
                block return 302 "https://$HTTP_HOST/en/"
        }

        # Redirect all other locations to the main page. Use $HTTP_HOST so TLS won't fail
        location * {
                block return 302 "https://$HTTP_HOST/"
        }

}
