server "cals.schmidbauer.cz" {
        alias "cards.schmidbauer.cz"
        listen on * port 80
        listen on * tls port 443

        # hardening
        tcp backlog 5
        connection {
                max request body 64000
                max requests 20
                request timeout 2
        }

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                #ciphers "HIGH:!CBC:!AES128:!kRSA:!aNULL"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/cals.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/cals.schmidbauer.cz.key"
        }

        # default redirect to radicale
        location "*" {
                block return 302 "https://cards.schmidbauer.cz:5232/.web/"
        }
}
