server "webmail.schmidbauer.cz" {
        listen on * tls port 443

        root "/rainloop"

        {% if httpd_block_bad_locations %}include '{{ httpd_bad_locations_path }}'{% endif %}

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/webmail.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/webmail.schmidbauer.cz.key"
        }

        directory {
                   index "index.php"
        }

        location "*.php*" {
                #fastcgi socket "/run/php-fpm.sock"
                fastcgi socket tcp 127.0.0.1 8000
        }

        location match "/data/(.*)" { block }
}
