server "blog.schmidbauer.cz" {
        listen on * tls port 443

        # allow 2G file size
        connection {
                max request body 2000000000
                max requests 20
                request timeout 300
        }

        root "htdocs/blog.schmidbauer.cz"

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/blog.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/blog.schmidbauer.cz.key"
                #ocsp "/etc/ssl/blog.schmidbauer.cz.der"
        }

}
