server "openpgpkey.schmidbauer.cz" {
        listen on * tls port 443

        root "/openpgpkey"
        {% if httpd_block_bad_locations %}include '{{ httpd_bad_locations_path }}'{% endif %}

        # OpenPGP Web Key Directory
        location "/.well-known/openpgpkey/*" {
          request strip 3
        }

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/openpgpkey.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/openpgpkey.schmidbauer.cz.key"
        }
}
