server "mail.schmidbauer.cz" {
        listen on * tls port 443

        tls {
                ciphers "EECDH+AESGCM:EDH+AESGCM"
                #ciphers "HIGH:!CBC:!AES128:!kRSA:!aNULL"
                ecdhe "P-384,P-256,X25519"
                certificate "/etc/ssl/mail.schmidbauer.cz.fullchain.pem"
                key "/etc/ssl/private/mail.schmidbauer.cz.key"
        }

        # drop bad locations
        include "/etc/httpd.bad-locations.conf"

        # redirect any HTTP to the webmail
        location * {
                block return 302 "https://webmail.schmidbauer.cz/"
        }
}
