fqdn: mail2.schmidbauer.cz
mail_domain: schmidbauer.cz
update: true

admins:
  - { name: puffy, pass: "$2b$09$OrnsezebLKBNuMqdhe7neujp8yvEKTvKPA3BDlZRVodNOCFRFYKse" , key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}" }

users:
  - { name: angelika, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }
  - { name: anna, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }
  - { name: hans, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }
  - { name: mattias, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }
  - { name: max, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }
  - { name: stefan, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }

host_aliases:
  - www2.schmidbauer.cz

ipv4_autoconf: true
ipv6_autoconf: true

ipv4_addr: 199.247.3.242
ipv4_netmask: 255.255.254.0
ipv4_gw: 199.247.2.1
#
ipv6_addr: 2001:19f0:6c01:2bde:5400:04ff:feda:e590
ipv6_netmask: /64
#ipv6_gw:

httpd_block_bad_locations: true
httpd_default_mime_types: true
httpd_use_tls: true # Only set to true once the certificate is actually generated!
httpd_use_lets_encrypt: true
httpd_enforce_tls: true # Except for Let's Encrypt that is
httpd_redirect_default_vhost: true
httpd_redirect_default_vhost_destination: https://webmail.schmidbauer.cz

mta_sts: false
