fqdn: mail2.schmidbauer.cz
mail_domain: schmidbauer.cz

admins:
  - { name: puffy, pass: $2b$09$rNEtwCuzLuvyIINfE1Z/EOZpusDJ21iI/RQRYOwBkc6cAJcXg7yOK , key: "{{ lookup('file', '~/.ssh/id_ecdsa.pub') }}" }

users:
  - { name: stefan,         pass: $2b$09$8dbRJ5mjxoVw1oAqgLR2sujIZKfnuBvZGtwlUJnVIakDsszhzpJgi }

host_aliases:
  - www2.schmidbauer.cz
  - stream2.schmidbauer.cz

ipv4: 199.247.23.59
ipv6: 2001:19f0:6c01:6b3:5400:02ff:feeb:91fc
ipv4_gw: 199.247.22.1
ipv6_gw: None
