fqdn: mail2.schmidbauer.cz
mail_domain: schmidbauer.cz
update: true

admins:
  - { name: puffy, pass: "$2b$09$OrnsezebLKBNuMqdhe7neujp8yvEKTvKPA3BDlZRVodNOCFRFYKse" , key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}" }

users:
  - { name: stefan, pass: "$2b$09$8Z9TxWQ3OMklHI1SEMHfcuqGjevVVYMBsT0LB9CN0PsgCyHrejAmO" }

host_aliases:
  - www2.schmidbauer.cz
  - ns2.schmidbauer.cz

ipv4_autoconf: true
ipv6_autoconf: true

# ipv4:
#   addr: 193.235.207.51
#   netmask: 255.255.255.0
#   gw: 193.235.207.1
#
# ipv6:
#   addr: 2001:19f0:6c01:6b3:5400:02ff:feeb:91fc
#   netmask: /64
#   gw:

httpd_use_tls: true # Only set to true once the certificate is actually generated!
httpd_use_lets_encrypt: true
httpd_enforce_tls: true # Except for Let's Encrypt that is
httpd_redirect_default_vhost: true
httpd_redirect_default_vhost_destination: https://webmail.schmidbauer.cz

mta_sts: true
